= Interesting facts about C
:toc:
 
== Fact 1
=== Void is non instantiable in C

Let's see the following code:
[void.c,c]
----
#include <stdio.h>

int main() {
  void a;
  printf("%d", a);
  return 1;
}
----

What output do you expect from the following code?

When you try to compile with `clang void.c` you'll get the following error:
[listing]
----
void.c:4:8: error: variable has incomplete type 'void'
    4 |   void a;
      |        ^
1 error generated.
----

This is because a void type has no value. Let's recall something about types. Let's say, we have 4 bits to work with. How many distinct values we could represent?

Starting from 0000 (=0) to 1111 (=15) we have 16 distinct values. We can also get the same number by 2^4 = 16.

Instead if we had n bits we could have 2^n distinct values. If we require to store k distinct values, it would be sufficient for us to use b = log2(k) bits, so that k = 2^b.

Instead if we have zero possible values we would require log2(0) number of bits, and log2(0) is undefined, and it cannot be instantiated in any way.

Now coming back to the point, since a void type in c has no possible value, thus it cannot be instantiated.

==== Then why some functions in C have return type as void? 

`void` represents an uninstantiable value, so the function cannot return anything, thus it's return value cannot be assigned to anything.

In an ideal world, returning from such a function should be impossible. However it's a quirk of a language that it allows it.

==== How this issue are addressed in other languages?

===== zig
In a similar langage called zig, instantiation of `void` is allowed. However, this `void` is a unit type, having only one possible value, the `void` itself. Since we have only one distinct type, number of bits required to represent it b = log2(1) = 0 bits. This makes sense because we always know it's the same value, so no bits are required for us to distinguish between different values.

Functions can return `void` and it can be assigned. However, since we are working with 0 bits, the resulting instruction is empty.

Consider the following program:
[void.zig, zig]
----
const std = @import("std");

pub fn main() void {
    const voidvalue: void = undefined;
    std.debug.print("Value: {}\n", .{voidvalue});
    std.debug.print("Size: {} bits\n", .{@bitSizeOf(@TypeOf(voidvalue))});
}
----

The output looks something like:
[listing]
----
Value: void
Size: 0 bits
----

Zig also offers a family of types called `opaque`, whose value are unknowable and cannot be instantiated.

==== rust
In another systems language called `rust`, there is unit type `()` which is the default return type of the function, which is equivalent to void type in zig.

Rust also contains another type called `never` represented by `!`. The usage of this type is exactly as it says, it's value are never expressed. It cannot, will not and should not exist.

One of the function that returns a never value is the function `exit()`. If you write like:
`let x = exit(32);` the function `exit()` never returns a value for `x` to be assigned. 

Likewise, infinite loops, an if expression with early return, all return a never type to it's assignee.

== Fact 2
=== Zero-bit type in C

You can instantiate a zero bit type in C as:

[zero-bit-type.c, c]
----
#include <stdio.h>

int main() {
    struct zero_bit_type {};
    struct zero_bit_type zbt;
    printf("Size of zero_bit_type: %zu bytes\n", sizeof(zbt));
}
----

Output:
----
Size of zero_bit_type: 0 bytes
----

NOTE: Support for empty structs in C is compiler dependent. However, in {cpp} they're supported and are guaranteed to take at least 1 byte in memory. Thus, empty structs (and their array) in C also happen to take 1 byte of memory per instantiation. However, if you apply the sizeof() operator, you will still get 0 bytes as the answer. Likewise, pointers to empty structs remain unchanged under pointer arithmetic.

Since the struct has no field, we don't have to assign any value while instantiating it. Believe it or not, this is the unit type in C because it has only one possible value.

If it feels hard to wrap around whether it has only one possible values or zero possible values, consider following demonstration.

How many values are possible for given struct:
----
struct char_wrapper {
  char c;
};
----
You are right, there are exactly 256 different possible values.

Now for the following struct?
----
struct two_chars {
  char a;
  char b;
};
----
We can see for each value of a, we have 256 different values of b. Thus all possible values of the struct two_chars is 256 * 256.

Now If we remove each field one by one we get:
----
struct zero_chars {
};
----

Naturally, by dividing the number of unique values for each types each time we remove it from the struct, by the time we get empty struct, we get number of possible values = 1.

Likewise:
What if we add empty struct field?
----
struct strange_char_wrapper{
  char c;
  struct {} nothing;
}
----
The number of possible values are still 256. This is only true when `struct {}` has only 1 possible value so that 256 * 1 = 256.

== Fact 3
=== Unorthodox way to access a value through a pointer.

  `pointer[index]` is same as `index[pointer]`

We can index a pointer `ptr` of type `T` with `idx` using the syntax `ptr[idx]`. 

This is a syntactic sugar for the pointer arithmetic: `*(ptr + i)` 

Since addition is commutative, we can also do: `*(i + ptr)`

Thus equivalently we can index as `idx[ptr]`. We can always interchange position of idx or ptr while using this notation, as long as one of them is pointer.

This is because `(ptr + i)` in pointer arithmetic actually resolves to `(ptr + i * offset)` in machine code, where `offset = sizeof(T)`. We can only know the offset if one of them is the pointer.

Thus instead of `*ptr` you can also `0[ptr]`.

== Fact 4
=== Assignment Expression in C.

Look at the following code snippet:
[assignment-expression.c, c]
----
#include<stdio.h>

int main() {
  int a;
  int b;
  int c = (a = 2) * (b = 3) + 5;

  // Following not valid in c, only valid in c++.
  // (b = 5) = 7;
  printf("Value (a) = %d\n", a);
  printf("Value (b) = %d\n", b);
  printf("Value (c) = %d\n", c);

  return 0;
}
----

What is the output do you expect from the above program?

When we actually run it, this is the output we get:
----
Value (a) = 2
Value (b) = 3
Value (c) = 11
----

Assignment operator (=), like any other operator returns a value, in this case the value that's being assigned is the return value.

==== C/{cpp} difference
The above program works both in C and {cpp} but if we uncomment the line above printf, it only compiles in {cpp}. That's because in {cpp} the (=) operator also returns a lvalue.

In {cpp} version, output is the variable itself from which we could extract its reference and do anything with it. In C, we only get the value, and assigning to it would make no sense.

== Fact 5
=== Comma Operator

Look at the following code snippet:

[comma-operator.c, c]
----
#include<stdio.h>

int main() {
  int a;
  int b;
  int c = (a = 2, b = 3, a+b);

  printf("Value (a) = %d\n", a);
  printf("Value (b) = %d\n", b);
  printf("Value (c) = %d\n", c);

  return 0;
}
----

In C, we also have a comma operator is left associate operator that returns the value to the right. This means, the left side expression is evaluated first (unlike the (=) operator where right side is evaluated first), so assignment is performed first. Since leftmost value is returned, we would expect to get an output of 5. Which is what we get:

Output:
----
Value (a) = 2
Value (b) = 3
Value (c) = 5
----

